import * as fs from "fs";
import * as path from "path";

function generateClientStub(rpName: string): string {
    return `${rpName}: createRpClientStub(apiBaseUrl, getToken, "${rpName}")`;
}

function generateClientStubs(rpNames: Array<string>): string {
    return rpNames.map(rpName => generateClientStub(rpName)).join(",\n        ");
}

export function generateClientFile(pathToAgDir: string, rpNames: Array<string>): void {
    const file = `// THIS FILE IS AUTOGENERATED.
// DO NOT EDIT IT.

import  { GetTokenFunc, createRpClientStub } from "@bognikol/rpapi/client";
import { RpDictionary } from "./RpDictionary.ag";

export * from "./RpDictionary.ag";
export * from "../types";

export function createRpapiClient(apiBaseUrl: string, getToken: GetTokenFunc): RpDictionary {
    return {
        ${generateClientStubs(rpNames)}
    };
}
`;

    const pathToClientFile = path.join(pathToAgDir, "client.ag.ts");
    fs.writeFileSync(pathToClientFile, file)
}
