import * as fs from "fs";
import * as path from "path";

function generateRpInterfaceImportExport(rpName: string): string {
    return `
import { ${rpName}Request, ${rpName}Response } from "../procedures/${rpName}.p";
export { ${rpName}Request, ${rpName}Response };
`;
}

function generateRpInterfaceImportExports(rpNames: Array<string>): string {
    return rpNames.map(rpName => generateRpInterfaceImportExport(rpName)).join("");
}

function generateRpDictionaryEntry(rpName: string): string {
    return `${rpName}: Rp<${rpName}Request, ${rpName}Response>`;
}

function generateRpDictionaryEntries(rpNames: Array<string>): string {
    return rpNames.map(rpName => generateRpDictionaryEntry(rpName)).join(",\n    ");
}

export function generateRpDictionaryFile(pathToAgDir: string, rpNames: Array<string>): void {
    const file = `// THIS FILE IS AUTOGENERATED.
// DO NOT EDIT IT.

import { Rp } from "@bognikol/rpapi";
export { Rp };
${generateRpInterfaceImportExports(rpNames)}

export interface RpDictionary {
    ${generateRpDictionaryEntries(rpNames)}
}
`;

    const pathToCommonFile = path.join(pathToAgDir, "RpDictionary.ag.ts");
    fs.writeFileSync(pathToCommonFile, file)
}
