import * as fs from "fs";
import * as path from "path";

function generateHandlerImport(rpName: string): string {
    return `import { ${rpName} } from "../procedures/${rpName}.p";`;
}

function generateHandlerImports(rpNames: Array<string>): string {
    return rpNames.map(rpName => generateHandlerImport(rpName)).join("\n");
}

function generateRpNames(rpNames: Array<string>): string {
    return rpNames.join(",\n        ");
}

export function generateServerFile(pathToAgDir: string, rpNames: Array<string>): void {
    const file = `// THIS FILE IS AUTOGENERATED.
// DO NOT EDIT IT.

import express from "express";
import { registerRpServer } from "@bognikol/rpapi/server";

${generateHandlerImports(rpNames)}

import { RpDictionary } from "./RpDictionary.ag";

export function createRpapiServer(app: express.Express): void {
    registerRpServer<RpDictionary>(app, {
        ${generateRpNames(rpNames)}
    });
}
`;

    const pathToServerFile = path.join(pathToAgDir, "server.ag.ts");
    fs.writeFileSync(pathToServerFile, file)
}